name: Verify the overlay using Vagrant

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  validate-profile:
    name: Validate profile
    runs-on: macos-latest
    strategy:
      matrix:
        suite: ['Win10MySQLOverlay']
      fail-fast: false
    env:
      CHEF_LICENSE: accept-silent
    steps:
      - name: Add jq for output formatting
        run: brew install jq
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Disable ri and rdoc
        run: 'echo "gem: --no-ri --no-rdoc" >> ~/.gemrc'
      - name: Setup caching
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle install
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install
      - name: Run kitchen test
        run: |
          cd test/cookbooks/Win10MySQLOverlay/
          bundle exec kitchen list --log-level=debug all || true
          bundle exec kitchen test --destroy=always --log-level=debug ${{ matrix.suite }} || true
      - name: Display our ${{ matrix.suite }} results summary
        run: |
          cd test/cookbooks/Win10MySQLOverlay/
          bundle exec inspec_tools summary -j ${{ matrix.suite }}-test-results.json --json-counts | jq .
      - name: Save Test Result JSON
        uses: actions/upload-artifact@v4
        with:
          path: test/cookbooks/Win10MySQLOverlay/*-results.json
          if-no-files-found: error
          name: ${{ matrix.suite }}-results
