name: Verify the overlay using Vagrant

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  validate-profile:
    name: Validate profile
    runs-on: macos-latest
    strategy:
      matrix:
        suite: ['Win10MySQLOverlay']
      fail-fast: false
    env:
      CHEF_LICENSE: accept-silent
    steps:
      - name: Add jq for output formatting
        run: brew install jq
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Disable ri and rdoc
        run: 'echo "gem: --no-ri --no-rdoc" >> ~/.gemrc'
      - name: Setup caching
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle install
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install
      - name: Run kitchen test
        run: |
          cd tests/cookbooks/Win10MySQLOverlay/
          bundle exec kitchen test ${{ matrix.suite }} 
      - name: Display our ${{ matrix.suite }} results summary
        run: |
          cd tests/cookbooks/Win10MySQLOverlay/
          bundle exec inspec_tools summary -j ${{ matrix.suite }}-results.json --json-counts | jq .
      - name: Save Test Result JSON
        uses: actions/upload-artifact@v2
        with:
          path: ./*-results.json

